version: '3.8'

services:
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      my-net:
        ipv4_address: 172.20.0.10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_END_POINT=172.20.0.10
    container_name: frontend
    networks:
      - my-net
    environment:
      - REACT_APP_END_POINT=172.20.0.10
    ports:
      - "8000:80"

networks:
  my-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
